#!/usr/bin/env bash
#
# usage: batch < bpar file > < bspar file >

# run all the instances - - - - - - - - - - - - - - - - - - - - - - - - - - -

set=resilient-data/tmp_smspp_*.nc
#set=plan4res-data/FirstSetofInstances/*.nc4

for what in ../../UCBlock/data/nc4/$set; do

    printf "[$what MetaConfig1.txt MetaConfig2.txt BSCfg.txt]: "
    ./compare_formulations $what MetaConfig1.txt MetaConfig2.txt BSCfg.txt

    retVal=$?
    if [ $retVal -ne 0 ]; then
      exit 1
    fi

done

# the end - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
