#!/usr/bin/env bash

# Canad - - - - - - - - - - - - - - - - - - - -

for f in data/Canad/*.dat
do 
./LDS_MMCF_test ${f} s
done

# Mnetgen - - - - - - - - - - - - - - - - - - - -

for i in 64
do
for j in 4 8 16 32 64
do
for (( h=1 ; h<13 ; h++ ))
do

./LDS_MMCF_test data/Mnetgen/$i-$j-$h m

done
done
done

for i in 128
do
for j in 4 8 16 32 64 128
do
for (( h=1 ; h<13 ; h++ ))
do

./LDS_MMCF_test data/Mnetgen/$i-$j-$h m

done
done
done

for i in 256
do
for j in 4 8 16 32 64 128 256
do
for (( h=1 ; h<13 ; h++ ))
do

./LDS_MMCF_test data/Mnetgen/$i-$j-$h m

done
done
done

# end batch
