image: alpine:3.10

#variables:
#  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apk update
  - apk add doxygen git
  - apk add texlive-full ghostscript
#  - apk add openssh-client
#  - eval $(ssh-agent -s)
#  - mkdir -p ~/.ssh
#  - echo "$SSH_PRIVATE_KEY" | ssh-add -
#  - ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts

test:
  script:
    - ./add_tokens.sh
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - doxygen doxygen/Doxyfile
  except:
    - master

pages:
  script:
    - ./add_tokens.sh
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - doxygen doxygen/Doxyfile
    - mv doc/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
