#!/bin/bash

# Function to install software on Ubuntu
install_on_ubuntu() {
  set -e # Exit immediately if a command exits with a non-zero status

  echo "Starting the installation process on Ubuntu..."

  # Update packages and install basic requirements
  echo "Updating system and installing basic requirements..."
  apt-get update
  apt-get install -y build-essential clang cmake git curl

  # Install Boost libraries
  echo "Installing Boost libraries..."
  apt-get install -y libboost-dev libboost-system-dev libboost-timer-dev libboost-mpi-dev libboost-random-dev

  # Install OpenMP
  apt-get install -y libomp-dev

  # Install Eigen
  echo "Installing Eigen..."
  apt-get install -y libeigen3-dev

  # Install NetCDF-C++
  echo "Installing NetCDF-C++..."
  apt-get install -y libnetcdf-c++4-dev

  # Install CPLEX
  echo "Installing CPLEX..."
  cd /opt
  CPLEX_INSTALLER="cplex_studio2211.linux_x86_64.bin"
  curl -O https://TODO/$CPLEX_INSTALLER
  chmod u+x $CPLEX_INSTALLER
  ./$CPLEX_INSTALLER
  rm $CPLEX_INSTALLER
  mv ./ibm/ILOG/CPLEX_Studio2211 /opt/ibm/ILOG/CPLEX_Studio
  export CPLEX_HOME="/opt/ibm/ILOG/CPLEX_Studio/cplex"
  export PATH="${PATH}:${CPLEX_HOME}/bin/x86-64_linux"
  export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${CPLEX_HOME}/lib/x86-64_linux"
  sh -c "echo '${CPLEX_HOME}/lib' > /etc/ld.so.conf.d/cplex.conf"
  ldconfig

  # Install Gurobi
  echo "Installing Gurobi..."
  cd /opt
  GUROBI_INSTALLER="gurobi10.0.3_linux64.tar.gz"
  curl -O https://packages.gurobi.com/10.0/$GUROBI_INSTALLER
  tar -xvf $GUROBI_INSTALLER
  rm $GUROBI_INSTALLER
  mv ./gurobi1003 /opt/gurobi
  export GUROBI_HOME="/opt/gurobi/linux64"
  export PATH="${PATH}:${GUROBI_HOME}/bin"
  export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${GUROBI_HOME}/lib"
  sh -c "echo '${GUROBI_HOME}/lib' > /etc/ld.so.conf.d/gurobi.conf"
  ldconfig

  # Install SCIP
  echo "Installing SCIP..."
  apt-get install -y gfortran libtbb-dev
  cd /opt
  SCIP_INSTALLER="SCIPOptSuite-9.0.0-Linux-ubuntu22.sh"
  curl -O https://www.scipopt.org/download/release/$SCIP_INSTALLER
  chmod u+x $SCIP_INSTALLER
  ./$SCIP_INSTALLER --prefix=/opt/scip --exclude-subdir --skip-license
  rm $SCIP_INSTALLER
  sh -c "echo '/opt/scip/lib' > /etc/ld.so.conf.d/scip.conf"
  ldconfig

  # Install HiGHS
  echo "Installing HiGHS..."
  cd /opt
  git clone https://github.com/ERGO-Code/HiGHS.git
  cd HiGHS
  mkdir build
  cd build
  cmake -DFAST_BUILD=ON -DCMAKE_INSTALL_PREFIX=/opt/HiGHS ..
  cmake --build .
  cmake --install .
  sh -c "echo '/opt/HiGHS/lib' > /etc/ld.so.conf.d/highs.conf"
  ldconfig
  cd /opt

  # Install COIN-OR CoinUtils and Osi/Clp
  echo "Installing COIN-OR CoinUtils and Osi/Clp..."
  apt-get install -y coinor-libcoinutils-dev libbz2-dev liblapack-dev libopenblas-dev
  cd /opt
  curl -O https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew
  chmod u+x coinbrew
  ./coinbrew build CoinUtils --latest-release --skip-dependencies --prefix=/opt/coin-or --tests=none
  ./coinbrew build Osi --latest-release --skip-dependencies --prefix=/opt/coin-or --tests=none --with-cplex --with-cplex-lib="-L$CPLEX_HOME/lib/x86-64_linux/static_pic -lcplex -lilocplex -lm -ldl -lpthread" --with-cplex-incdir="$CPLEX_HOME/include/ilcplex" --with-gurobi --with-gurobi-lib="-L$GUROBI_HOME/lib -lgurobi100" --with-gurobi-incdir="$GUROBI_HOME/include"
  ./coinbrew build Clp --latest-release --skip-dependencies --prefix=/opt/coin-or --tests=none
  rm -R coinbrew build
  export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/coin-or/lib"
  ldconfig

  # Install StOpt
  echo "Installing StOpt..."
  apt-get install -y zlib1g-dev
  cd /opt
  git clone https://gitlab.com/stochastic-control/StOpt
  cd StOpt
  mkdir build
  cd build
  cmake -DBUILD_PYTHON=OFF -DBUILD_TEST=OFF -DCMAKE_INSTALL_PREFIX=/opt/StOpt ..
  cmake --build .
  cmake --install .
  cd /opt

  echo "Installation completed successfully on Ubuntu."
}

# Function to install software on macOS
install_on_macos() {
  set -e # Exit immediately if a command exits with a non-zero status

  echo "Starting the installation process on macOS..."

  # Install Homebrew
  echo "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  # Install Xcode Command Line Tools (includes build-essential and clang)
  echo "Installing Xcode Command Line Tools..."
  xcode-select --install

  # Install basic requirements
  echo "Installing basic requirements..."
  brew install cmake git

  # Install Boost libraries
  echo "Installing Boost libraries..."
  brew install boost

  # Install OpenMP
  brew install libomp

  # Install Eigen
  echo "Installing Eigen..."
  brew install eigen

  # Install NetCDF
  echo "Installing NetCDF..."
  brew install netcdf

  # Install CPLEX
  echo "Installing CPLEX..."
  cd /Applications
  CPLEX_INSTALLER="cplex_studio2211.osx.zip"
  curl -O https://TODO/$CPLEX_INSTALLER
  tar -xvf $CPLEX_INSTALLER
  # TODO
  rm $CPLEX_INSTALLER
  mv ./CPLEX_Studio2211 /Applications/CPLEX_Studio
  export CPLEX_HOME="/Applications/CPLEX_Studio"
  export PATH="${PATH}:${CPLEX_HOME}/bin/x86-64_osx"
  export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}:${CPLEX_HOME}/lib/x86-64_osx"
  ldconfig

  # Install Gurobi
  echo "Installing Gurobi..."
  cd /Library
  GUROBI_INSTALLER="gurobi10.0.3_macos_universal2.pkg"
  curl -O https://packages.gurobi.com/10.0/$GUROBI_INSTALLER
  installer -pkg $GUROBI_INSTALLER -target /
  rm $GUROBI_INSTALLER
  mv ./gurobi1003 /Library/gurobi
  export GUROBI_HOME="/Library/gurobi"
  export PATH="${PATH}:${GUROBI_HOME}/bin"
  export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}:${GUROBI_HOME}/lib"
  ldconfig

  # Install SCIP
  echo "Installing SCIP..."
  brew install gcc tbb
  SCIP_INSTALLER="SCIPOptSuite-9.0.0-Darwin.sh"
  curl -O https://www.scipopt.org/download/release/$SCIP_INSTALLER
  chmod u+x $SCIP_INSTALLER
  ./$SCIP_INSTALLER --prefix=/Library/scip --exclude-subdir --skip-license
  rm $SCIP_INSTALLER

  # Install HiGHS
  echo "Installing HiGHS..."
  cd /Library
  git clone https://github.com/ERGO-Code/HiGHS.git
  cd HiGHS
  mkdir build
  cd build
  cmake -DFAST_BUILD=ON -DCMAKE_INSTALL_PREFIX=/Library/HiGHS ..
  cmake --build .
  cmake --install .
  cd /Library

  # Install COIN-OR CoinUtils and Osi/Clp
  echo "Installing COIN-OR CoinUtils and Osi/Clp..."
  brew install coinutils bz2 lapack openblas
  cd /Library
  curl -O https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew
  chmod u+x coinbrew
  ./coinbrew fetch CoinUtils --no-prompt
  ./coinbrew build CoinUtils --prefix=/Library/coin-or --no-prompt --tests=none
  ./coinbrew build Osi --prefix=/Library/coin-or --no-prompt --tests=none --with-cplex --with-cplex-lib="-L$CPLEX_HOME/lib/x86-64_osx/static_pic -lcplex -lilocplex -lm -ldl -lpthread" --with-cplex-incdir="$CPLEX_HOME/include/ilcplex" --with-gurobi --with-gurobi-lib="-L$GUROBI_HOME/lib -lgurobi100" --with-gurobi-incdir="$GUROBI_HOME/include"
  ./coinbrew build Clp --prefix=/Library/coin-or --no-prompt --tests=none
  rm -R coinbrew build

  # Install StOpt
  echo "Installing StOpt..."
  brew install zlib
  cd /Library
  git clone https://gitlab.com/stochastic-control/StOpt
  cd StOpt
  mkdir build
  cd build
  cmake -DBUILD_PYTHON=OFF -DBUILD_TEST=OFF -DCMAKE_INSTALL_PREFIX=/Library/StOpt ..
  cmake --build .
  cmake --install .
  cd /Library

  echo "Installation completed successfully on macOS."
}

# Function to install software on Windows
# RUN THIS SCRIPT FROM A "DEVELOPER POWERSHELL FOR VS" AS ADMINISTRATOR
# VISUAL STUDIO WITH THE ENGLISH LANGUAGE PACK IS NEEDED
function install_on_windows() {
  cd C:\

  echo "Starting the installation process on Windows..."

  # Install basic requirements
  echo "Installing basic requirements..."
  Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
  choco install git sed
  Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
  refreshenv

  # Install vcpkg
  echo "Installing vcpkg..."
  cd C:\
  git clone https://github.com/microsoft/vcpkg.git
  cd C:\vcpkg
  ./bootstrap-vcpkg.bat

  # Install basic requirements
  echo "Installing basic requirements with vcpkg..."
  ./vcpkg install zlib bzip2 pthreads getopt --triplet x64-windows

  # Install Boost libraries
  echo "Installing Boost libraries..."
  ./vcpkg install boost --triplet x64-windows
  # to install boost-mpi you will need to run msmpisetup-10.1.12498.exe before
  Start-Process -FilePath "C:\vcpkg\downloads\msmpisetup-10.1.12498.exe" -Wait
  ./vcpkg install boost-mpi --triplet x64-windows

  # Install Eigen
  echo "Installing Eigen..."
  ./vcpkg install eigen3 --triplet x64-windows

  # Install NetCDF
  echo "Installing NetCDF..."
  ./vcpkg install netcdf-cxx4 --triplet x64-windows

  # Install CPLEX
  echo "Installing CPLEX..."
  cd C:\
  CPLEX_INSTALLER="cplex_studio2211.win_x86_64.exe"
  curl -O $CPLEX_INSTALLER https://TODO/$CPLEX_INSTALLER
  Start-Process -FilePath $CPLEX_INSTALLER -Wait
  rm $CPLEX_INSTALLER
  # copy from C:\Program Files to under C:\ to avoid errors due to spaces
  cp -R "C:\Program Files\IBM" "C:\IBM"
  mv "C:\IBM\ILOG\CPLEX_Studio2211" "C:\IBM\ILOG\CPLEX_Studio"

  # Install Gurobi
  echo "Installing Gurobi..."
  cd C:\
  GUROBI_INSTALLER="Gurobi-10.0.3-win64.msi"
  curl -O $GUROBI_INSTALLER https://packages.gurobi.com/10.0/$GUROBI_INSTALLER
  Start-Process -FilePath "msiexec.exe" -ArgumentList "/i", $GUROBI_INSTALLER -Wait
  rm $GUROBI_INSTALLER
  mv .\gurobi1003 C:\gurobi

  # Install SCIP
  echo "Installing SCIP..."
  cd C:\
  SCIP_INSTALLER="SCIPOptSuite-9.0.0-win64-VS15.exe"
  curl -O $SCIP_INSTALLER https://www.scipopt.org/download/release/$SCIP_INSTALLER
  Start-Process -FilePath $SCIP_INSTALLER -Wait
  rm $SCIP_INSTALLER
  mv "C:\Program Files\SCIPOptSuite 9.0.0" "C:\Program Files\SCIPOptSuite"

  # Install HiGHS
  echo "Installing HiGHS..."
  cd C:\
  git clone https://github.com/ERGO-Code/HiGHS.git
  cd HiGHS
  mkdir build
  cd build
  # link vcpkg toolchain file for zlib
  cmake -DFAST_BUILD=ON -DCMAKE_INSTALL_PREFIX=C:/HiGHS -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  cmake --build . --config Release
  cmake --install .
  cd C:\

  # Install COIN-OR CoinUtils
  echo "Installing COIN-OR CoinUtils..."
  cd C:\vcpkg
  ./vcpkg install coinutils blas lapack --triplet x64-windows

  echo "Modifying COIN-OR Osi portfile.cmake for CPLEX support..."

  cd C:\vcpkg\ports\coin-or-osi

  # Backup the original portfile.cmake just in case
  cp portfile.cmake portfile.cmake.bak

  # Use sed `/old/c\new` to replace the configuration line
  sed -i '/--without-cplex/c\
          --with-cplex\
          --with-cplex-lib=C:\\\/IBM\\\/ILOG\\\/CPLEX_Studio\\\/cplex\\\/lib\\\/x64_windows_msvc14\\\/stat_mda\\\/cplex2211.lib\
          --with-cplex-incdir=C:\\\/IBM\\\/ILOG\\\/CPLEX_Studio\\\/cplex\\\/include\\\/ilcplex\
          --with-cplex-cflags=-IC:\\\/IBM\\\/ILOG\\\/CPLEX_Studio\\\/cplex\\\/include\\\/ilcplex\
          --with-cplex-lflags=C:\\\/IBM\\\/ILOG\\\/CPLEX_Studio\\\/cplex\\\/lib\\\/x64_windows_msvc14\\\/stat_mda\\\/cplex2211.lib' portfile.cmake

  echo "COIN-OR Osi portfile modified for CPLEX support."

  echo "Modifying COIN-OR Osi portfile.cmake for Gurobi support..."

  # Use sed `/old/c\new` to replace the configuration line
  sed -i '/--without-gurobi/c\
          --with-gurobi\
          --with-gurobi-lib=C:\\\/gurobi\\\/win64\\\/lib\\\/gurobi100.lib\
          --with-gurobi-incdir=C:\\\/gurobi\\\/win64\\\/include\
          --with-gurobi-cflags=-IC:\\\/gurobi\\\/win64\\\/include\
          --with-gurobi-lflags=C:\\\/gurobi\\\/win64\\\/lib\\\/gurobi100.lib' portfile.cmake

  echo "COIN-OR Osi portfile modified for Gurobi support."

  # Install COIN-OR Osi/Clp
  echo "Installing COIN-OR Osi with CPLEX and Gurobi support..."
  cd C:\vcpkg
  ./vcpkg install coin-or-osi coin-or-clp glpk --triplet x64-windows

  # Setup vcpkg for StOpt installation
  echo "Setting up vcpkg for StOpt installation..."
  cd C:\
  git clone https://gitlab.com/stochastic-control/vcpkg-registry
  cd C:\vcpkg

  # Install StOpt using custom vcpkg registry
  echo "Installing StOpt..."
  ./vcpkg install stopt --overlay-ports=C:\vcpkg-registry\ports\stopt --triplet x64-windows
  rm -R C:\vcpkg-registry

  echo "Installation completed successfully on Windows."
}

# Detect operating system and execute the appropriate installation function
OS="$(uname)"
case "$OS" in
"Linux")
  if [ -f /etc/lsb-release ]; then
    . /etc/lsb-release
    if [ "$DISTRIB_ID" = "Ubuntu" ]; then
      install_on_ubuntu
      mkdir build
      cd build
      cmake -DCMAKE_INSTALL_PREFIX=/opt/SMSpp  -DCMAKE_BUILD_TYPE=Release ..
    else
      echo "This script supports Ubuntu only."
    fi
  else
    echo "This script supports Ubuntu only."
  fi
  ;;
"Darwin")
  install_on_macos
  mkdir build
  cd build
  cmake -DCMAKE_INSTALL_PREFIX=/Library/SMSpp -DCMAKE_BUILD_TYPE=Release ..
  ;;
"Windows")
  install_on_windows
  mkdir build
  cd build
  cmake -DCMAKE_INSTALL_PREFIX=C:/SMSpp -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -Wno-dev ..
  ;;
*)
  echo "This script does not support the detected operating system."
  ;;
esac

# Compile SMSpp
echo "Compiling SMSpp..."
cmake --build . --config Release
cmake --install .
cd ..
