#!/usr/bin/env bash

#for what in ../../UCBlock/netCDF_files/plan4res-data/France/WeekAgr/*.nc4; do
for what in ../../UCBlock/netCDF_files/plan4res-data/France/WeekDesAgr/*.nc4; do

  printf "[$what]: "

  ./LDS_UC_test $what

  retVal=$?
  if [ $retVal -ne 0 ]; then
    exit 1
  fi

done
