#!/usr/bin/env bash

# runs all the academic instances: intended for being used when the
# ThermalUnitBlock subproblems are solved to integer optimality
# (typically using ThermalUnitDPSolver, although a :MILPSolver would
# be a less efficient option)

cp ./TUBCfg-DP.txt ./TUBCfg.txt 
cp ./TUBSCfg-DP.txt ./TUBSCfg.txt 

# correct value of tStar: 1e+0

folder=./data/UC_Data/T-Ramp/
par=BSPar-2S.txt
#mlf=log.txt

for size in 10 20 50; do
  for (( seed = 1 ; seed < 6 ; seed++ )); do

    if [ -z "$par" ]; then
      if [ -z "$mlf" ]; then
        printf "[$folder${size}_0_${seed}_w.nc4]: "
      else
        printf "[$folder${size}_0_${seed}_w.nc4]: " >> $mlf
      fi
    else
      if [ -z "$mlf" ]; then
        printf "[$folder${size}_0_${seed}_w.nc4 $par]: "
      else
        printf "[$folder${size}_0_${seed}_w.nc4 $par]: " >> $mlf
      fi
    fi

    if [ -z "$mlf" ]; then
      ./LDS_UC_test $folder${size}_0_${seed}_w.nc4 $par
    else
      ./LDS_UC_test $folder${size}_0_${seed}_w.nc4 $par >> $mlf
    fi

    retVal=$?
    if [ $retVal -ne 0 ]; then
      exit 1
    fi

  done
done

# end batch
