#!/usr/bin/env bash
#
# usage: batch_ec < par file > < log file >
#        < par file > = BlockSolverConfig file, default BSPar-2S.txt
#        < log file > = name of log file, default no log
#
# runs all the pure energy community instances

# command line parameter setup- - - - - - - - - - - - - - - - - - - - - - - -

if [ $# -gt 0 ]; then
   par=$1
else
   par=BSPar-2S.txt
fi
if [ $# -gt 1 ]; then
   mlf=$2
fi

# run all the instances - - - - - - - - - - - - - - - - - - - - - - - - - - -

for what in ../../UCBlock/netCDF_files/EC_Data/EC*.nc4 ; do

    if [ -z "$par" ]; then
      if [ -z "$mlf" ]; then
        printf "[$what]: "
      else
        printf "[$what]: " >> $mlf
      fi
    else
      if [ -z "$mlf" ]; then
        printf "[$what $par]: "
      else
        printf "[$what $par]: " >> $mlf
      fi
    fi

    if [ -z "$mlf" ]; then
      ./LDS_UC_test $what $par
    else
      ./LDS_UC_test $what $par >> $mlf
    fi

    retVal=$?
    if [ $retVal -ne 0 ]; then
      exit 1
    fi

done

# the end - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
