#!/usr/bin/env bash
#
# usage: batch_acad < exe file > < par file >  < solver > < log file >
#        < exe file > = path of the executable file, default LDS_UC_test
#        < par file > = BlockSolverConfig file, default BSPar-2S.txt
#        < solver > = 0 or 1, default 0
#        < log file > = name of log file, default no log
#
# runs all the pure energy community instances

# command line parameter setup- - - - - - - - - - - - - - - - - - - - - - - -

if [ $# -gt 0 ]; then
   exe=$1
else
   exe=./LDS_UC_test
fi
if [ $# -gt 1 ]; then
   par=$2
else
   par=BSPar-2S.txt
fi
if [ $# -gt 2 ]; then
   slv=$3
else
   slv=0
fi
if [ $# -gt 3 ]; then
   mlf=$4
fi

# run all the instances - - - - - - - - - - - - - - - - - - - - - - - - - - -

for what in ../../UCBlock/data/nc4/EC_Data/EC_CO_*.nc4 \
            ../../UCBlock/data/nc4/EC_Data/EC_NC_*.nc4; do

    if [ -z "$mlf" ]; then
       printf "[$what $par $slv]: "
       "$exe" $what $par $slv
    else
       printf "[$what $par $slv]: " >> $mlf
       "$exe" $what $par $slv >> $mlf
    fi

    retVal=$?
    if [ $retVal -ne 0 ]; then
      exit 1
    fi

done

# the end - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
