#!/usr/bin/env bash
#
# usage: batch_acad < par file > < log file >
#        < par file > = BlockSolverConfig file, default BSPar-2S.txt
#        < log file > = name of log file, default no log
#
# runs all pure thermal and hydrothermal academic instances
#
# for LagranngianDualSolver + BundleSolver:
# correct value of tStar: 1e+0

# command line parameter setup- - - - - - - - - - - - - - - - - - - - - - - -

if [ $# -gt 0 ]; then
   par=$1
else
   par=BSPar-2S.txt
fi
if [ $# -gt 1 ]; then
   mlf=$2
fi

#  pure thermal academic instances- - - - - - - - - - - - - - - - - - - - - -

DATADIR=../../UCBlock/netCDF_files/UC_Data/T-Ramp

for size in 10 20 50 75 100 200; do
  for (( seed = 1 ; seed < 6 ; seed++ )); do

    what=${DATADIR}/${size}_0_${seed}_w.nc4

    if [ -z "$par" ]; then
      if [ -z "$mlf" ]; then
        printf "[$what]: "
      else
        printf "[$what]: " >> $mlf
      fi
    else
      if [ -z "$mlf" ]; then
        printf "[$what $par]: "
      else
        printf "[$what $par]: " >> $mlf
      fi
    fi

    if [ -z "$mlf" ]; then
      ./LDS_UC_test $what $par
    else
      ./LDS_UC_test $what $par >> $mlf
    fi

    retVal=$?
    if [ $retVal -ne 0 ]; then
      exit 1
    fi

  done
done

# hydrothermal academic instances - - - - - - - - - - - - - - - - - - - - - -

DATADIR=../../UCBlock/netCDF_files/UC_Data/HT-Ramp

for size in 20_10 50_20 75_35 100_50 150_75 200_100; do
  for (( seed = 1 ; seed < 3 ; seed++ )); do

    what=${DATADIR}/${size}_${seed}_w.nc4

    if [ -z "$par" ]; then
      if [ -z "$mlf" ]; then
        printf "[$what]: "
      else
        printf "[$what]: " >> $mlf
      fi
    else
      if [ -z "$mlf" ]; then
        printf "[$what $par]: "
      else
        printf "[$what $par]: " >> $mlf
      fi
    fi

    if [ -z "$mlf" ]; then
      ./LDS_UC_test $what $par
    else
      ./LDS_UC_test $what $par >> $mlf
    fi

    retVal=$?
    if [ $retVal -ne 0 ]; then
      exit 1
    fi

  done
done

# the end - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
