#!/usr/bin/env bash
#
# usage: metabatch < par file > < exe file > < log file >
#        < par file > = BlockSolverConfig file, default BSPar.txt
#        < exe file > = path of the executable file, default ./LDS_UC_test
#        < log file > = name of log file, default none
#
# runs all the instances with < solver > == 0 (LagrangianDualSolver)

# command line parameter setup- - - - - - - - - - - - - - - - - - - - - - - -

if [ $# -gt 0 ]; then
   par=$1
else
   par=BSPar-2S.txt
fi
if [ $# -gt 1 ]; then
   exe=$2
else
   exe=./LDS_UC_test
fi
if [ $# -gt 2 ]; then
   mlf=$3
fi
slv=0

# run academic instances
./batches/batch-acad $exe $par $slv $mlf

# run plan4res instances
./batches/batch-p4r $exe $par $slv $mlf

# run energy community instances
./batches/batch-ec $exe $par $slv $mlf

# the end - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
