#!/usr/bin/env bash
#
# usage: metabatch-PPH < par file > < exe file > < log file >
#        < par file > = BlockSolverConfig file, default PrimalProximal.txt
#        < log file > = name of log file, default none
#        < exe file > = path of the executable file, default none
#
# runs all the instances with < solver > == 1 (PrimalProximalHeur)

# command line parameter setup- - - - - - - - - - - - - - - - - - - - - - - -

if [ $# -gt 0 ]; then
   par=$1
else
   par=ProxHeur-2S.txt
fi
if [ $# -gt 1 ]; then
   exe=$2
else
   exe=${1:~./LDS_UC_test}
fi
if [ $# -gt 2 ]; then
   exe=$3
fi
slv=1

# run academic instances
./batches/batch-acad $exe $par $slv $mlf

# run plan4res instances
./batches/batch-p4r $exe $par $slv $mlf

# run energy community instances
./batches/batch-ec $exe $par $slv $mlf

# the end - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
