#!/usr/bin/env bash

what=133
#iter=0

# simple thermals - - - - - - - - - - - - - - - - - - - - -

for wf in 8 9 10 11 12 13
do
for (( h=1 ; h<=98 ; h++ ))
do
for (( seed=0 ; seed<20 ; seed++ ))
do
#seed=0

if [ -z "$iter" ]; then
printf "[./simple/ThermalUnitBlock-${h}.nc4 $seed $what $wf]: "
else
printf "[./simple/ThermalUnitBlock-${h}.nc4 $seed $what $wf $iter]: "
fi

./TUDPS_test ./simple/ThermalUnitBlock-${h}.nc4 $seed $what $wf $iter

retVal=$?
if [ $retVal -ne 0 ]; then
    exit 1
fi

done
done
done

# end batch
