

#/bin/bash -l
nice
 
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p33.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p34.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p35.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p36.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p37.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p38.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p39.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p40.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p41.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p42.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p43.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p44.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p45.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p46.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p47.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p48.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p49.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p50.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p51.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p52.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p53.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p54.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p55.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p56.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p57.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p58.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p59.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p60.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p61.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p62.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p63.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Canad/p64.dat s
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.4/64-4-1 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.4/64-4-2 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.4/64-4-3 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.4/64-4-4 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.4/64-4-5 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.4/64-4-6 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.4/64-4-7 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.4/64-4-8 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.4/64-4-9 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.4/64-4-10 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.4/64-4-11 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.4/64-4-12 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.8/64-8-1 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.8/64-8-2 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.8/64-8-3 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.8/64-8-4 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.8/64-8-5 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.8/64-8-6 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.8/64-8-7 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.8/64-8-8 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.8/64-8-9 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.8/64-8-10 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.8/64-8-11 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.8/64-8-12 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.16/64-16-1 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.16/64-16-2 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.16/64-16-3 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.16/64-16-4 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.16/64-16-5 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.16/64-16-6 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.16/64-16-7 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.16/64-16-8 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.16/64-16-9 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.16/64-16-10 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.16/64-16-11 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.16/64-16-12 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.32/64-32-1 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.32/64-32-2 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.32/64-32-3 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.32/64-32-4 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.32/64-32-5 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.32/64-32-6 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.32/64-32-7 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.32/64-32-8 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.32/64-32-9 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.32/64-32-10 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.32/64-32-11 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.32/64-32-12 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.64/64-64-1 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.64/64-64-2 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.64/64-64-3 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.64/64-64-4 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.64/64-64-5 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.64/64-64-6 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.64/64-64-7 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.64/64-64-8 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.64/64-64-9 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.64/64-64-10 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.64/64-64-11 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/Mnetgen/pr64.64/64-64-12 m
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/JLF/Chen.PSP/psp1 p
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/JLF/Chen.PSP/psp2 p
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/JLF/Chen.PSP/psp3 p
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/JLF/Chen.PSP/psp4 p
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/JLF/Chen.PSP/psp5 p
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/JLF/Chen.PSP/psp6 p
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/JLF/Chen.PSP/psp7 p
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/JLF/Chen.DSP/chen0 p
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/JLF/Chen.DSP/chen1 p
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/JLF/Chen.DSP/chen2 p
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/JLF/Chen.DSP/chen3 p
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/JLF/Chen.DSP/chen4 p
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/JLF/Chen.DSP/chen5 p
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/JLF/Chen.DSP/chen6 p
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/JLF/Assad/assad1.5k p
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/JLF/Assad/assad1.6k p
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/JLF/Assad/assad3.4k p
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/JLF/Assad/assad3.7k p
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/JLF/ALK/alk.HALF p
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/JLF/ALK/alk.TWO p
./../MMCFtest ./test.mmcf ~/Programming/TestProblems/JLF/Powell/veh8 p
