#!/usr/bin/env bash

DATADIR=./ObjQ_ConsL
TYPE=I

quad_test=${1:-./quad_test}

for entry in "$DATADIR"/*; do

  printf "./quad_test $entry $TYPE: "

  "$quad_test" $entry $TYPE

  retVal=$?
  if [ $retVal -ne 0 ]; then
    exit 1
  fi

done
